### ISSUE TITLE
issue with up and running

### ISSUE THREAD

**Issue by crazynet** [philsturgeon/json-schema-to-openapi-schema#11]
I have followed the steps mentioned in the index page to download the module on ubuntu.
after that I created a file test.js with
```
const toOpenApi = require('json-schema-to-openapi-schema');

const schema = {
  '$schema': 'http://json-schema.org/draft-04/schema#',
  type: ['string', 'null'],
  format: 'date-time',
};

const convertedSchema = toOpenApi(schema);

console.log(convertedSchema);
```

when I am trying to run as below.

nodejs test.js I am getting the below error.

/home/developer/json/node_modules/json-schema-to-openapi-schema/index.js:10
function convert(schema, options = {}) {
                                 ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/developer/json/test.js:1:81)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

Please help if I am missing anything.

**Comment by philsturgeon** [comment]
This looks a lot like its an old version of node. Update it and you should be fine. :)
